### PR TITLE
OM-2446 - added sync off feature

### PR DESCRIPTION
**Pull request by creotiv**
This change is [Reviewable](https://reviewable.io/reviews/orzo-corp/neo4j-elasticsearch/1)

### CODE REVIEW

**Comment by prseshad** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/org/neo4j/elasticsearch/ElasticSearchEventHandler.java, line 147 at r1](https://reviewable.io:443/reviews/orzo-corp/neo4j-elasticsearch/1#-KW9NHUyfdjEaKJt_ecS:-KW9NHUzIeaq2cCP_KPT:b-7s8x9z) ([raw file](https://github.com/orzo-corp/neo4j-elasticsearch/blob/1d49cea54ef160af36e54a239c5a009d6809752f/src/main/java/org/neo4j/elasticsearch/ElasticSearchEventHandler.java#L147)):*
> ```Java
>         Set<Node> processedNodes = Sets.newHashSet();
>         for (NodeDetail node : nodes) {
>             // raising transaction roll back
> ```

Please remove this commented-out code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/orzo-corp/neo4j-elasticsearch/1)*

**Comment by prseshad** [comment]
Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/orzo-corp/neo4j-elasticsearch/1)*

**Comment by prseshad** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/org/neo4j/elasticsearch/ElasticSearchEventHandler.java, line 132 at r1](https://reviewable.io:443/reviews/orzo-corp/neo4j-elasticsearch/1#-KW9PD1BRgXv1HS6uwyd:-KW9PD1BRgXv1HS6uwye:busfgd5) ([raw file](https://github.com/orzo-corp/neo4j-elasticsearch/blob/1d49cea54ef160af36e54a239c5a009d6809752f/src/main/java/org/neo4j/elasticsearch/ElasticSearchEventHandler.java#L132)):*
> ```Java
>     private boolean useAsyncJest = false;
>     private final ObjectMapper jsonMapper = new ObjectMapper();
>     private Set<String> disabledIndexes = new HashSet<String>();
> ```

I don't think this can be a member of ElasticSearchEventHandler, because the handler gets instantiated only once, in the init() function of ElasticSearchExtension.java, when the db server starts, and it can be called by multiple threads executing multiple transactions at once, so the data structure cannot be common to all transactions.  Also disabledIndexes needs to be empty at the beginning of each call to beforeCommit.  So disabledIndexes needs to be local to beforeCommit, instantiated there, and passed into the functions where it is needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/orzo-corp/neo4j-elasticsearch/1)*

**Comment by creotiv** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/org/neo4j/elasticsearch/ElasticSearchEventHandler.java, line 132 at r1](https://reviewable.io:443/reviews/orzo-corp/neo4j-elasticsearch/1#-KW9PD1BRgXv1HS6uwyd:-KWD2_fGi4hs9KEsng2y:b-896fix) ([raw file](https://github.com/orzo-corp/neo4j-elasticsearch/blob/1d49cea54ef160af36e54a239c5a009d6809752f/src/main/java/org/neo4j/elasticsearch/ElasticSearchEventHandler.java#L132)):*
<details><summary><i>Previously, prseshad wrote…</i></summary>
> I don't think this can be a member of ElasticSearchEventHandler, because the handler gets instantiated only once, in the init() function of ElasticSearchExtension.java, when the db server starts, and it can be called by multiple threads executing multiple transactions at once, so the data structure cannot be common to all transactions.  Also disabledIndexes needs to be empty at the beginning of each call to beforeCommit.  So disabledIndexes needs to be local to beforeCommit, instantiated there, and passed into the functions where it is needed.
</details>
Done.

---

*[src/main/java/org/neo4j/elasticsearch/ElasticSearchEventHandler.java, line 147 at r1](https://reviewable.io:443/reviews/orzo-corp/neo4j-elasticsearch/1#-KW9NHUyfdjEaKJt_ecS:-KWD2aQLaD-qzp2BP5mv:b-896fix) ([raw file](https://github.com/orzo-corp/neo4j-elasticsearch/blob/1d49cea54ef160af36e54a239c5a009d6809752f/src/main/java/org/neo4j/elasticsearch/ElasticSearchEventHandler.java#L147)):*
<details><summary><i>Previously, prseshad wrote…</i></summary>
> Please remove this commented-out code.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/orzo-corp/neo4j-elasticsearch/1)*

**Comment by prseshad** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/orzo-corp/neo4j-elasticsearch/1)*

**Pull request merged**
